version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/CourseCompass/backend/src
    depends_on:
      - db
    environment:
      DATABASE_NAME: proyecto-desarrollo-web
      DATABASE_USER: postgres
      DATABASE_PASSWORD: banana
      DATABASE_HOST: bd
      DATABASE_PORT: 5432

  db:
    image: postgres
    environment:
      POSTGRES_DB: proyecto-desarrollo-web
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: banana
